// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/shijuvar/gokit/examples/testing/httpbdd/model (interfaces: UserStore)

// Package controllers_test is a generated GoMock package.
package controllers_test

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/shijuvar/gokit/examples/testing/httpbdd/model"
	reflect "reflect"
)

// MockUserStore is a mock of UserStore interface
type MockUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserStoreMockRecorder
}

// MockUserStoreMockRecorder is the mock recorder for MockUserStore
type MockUserStoreMockRecorder struct {
	mock *MockUserStore
}

// NewMockUserStore creates a new mock instance
func NewMockUserStore(ctrl *gomock.Controller) *MockUserStore {
	mock := &MockUserStore{ctrl: ctrl}
	mock.recorder = &MockUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserStore) EXPECT() *MockUserStoreMockRecorder {
	return m.recorder
}

// AddUser mocks base method
func (m *MockUserStore) AddUser(arg0 model.User) error {
	ret := m.ctrl.Call(m, "AddUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser
func (mr *MockUserStoreMockRecorder) AddUser(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockUserStore)(nil).AddUser), arg0)
}

// GetUsers mocks base method
func (m *MockUserStore) GetUsers() []model.User {
	ret := m.ctrl.Call(m, "GetUsers")
	ret0, _ := ret[0].([]model.User)
	return ret0
}

// GetUsers indicates an expected call of GetUsers
func (mr *MockUserStoreMockRecorder) GetUsers() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockUserStore)(nil).GetUsers))
}
