package main

import (
	"fmt"
	"math"
	"math/rand"
	"sync"
)

type fibvalue struct {
	input, value int
}

var wg sync.WaitGroup

// Generates random values
func randomCounter(out chan int) {
	defer wg.Done()
	var random int
	for x := 0; x < 10; x++ {
		random = rand.Intn(50)
		out <- random
	}
	close(out)
}

// Produces fibonacci values of inputs provided by randomCounter
func generateFibonacci(out chan fibvalue, in chan int) {
	defer wg.Done()
	var input float64
	for v := range in {
		input = float64(v)
		// Fibonacci using Binet's formula
		Phi := (1 + math.Sqrt(5)) / 2
		phi := (1 - math.Sqrt(5)) / 2
		result := (math.Pow(Phi, input) - math.Pow(phi, input)) / math.Sqrt(5)
		out <- fibvalue{
			input: v,
			value: int(result),
		}
	}
	close(out)
}

// Print fibonacci values generated by generateFibonacci
func printFibonacci(in chan fibvalue) {
	defer wg.Done()
	for v := range in {
		fmt.Printf("Fibonacci value of %d is %d\n", v.input, v.value)
	}
}

func main() {
	// Add 3 into WaitGroup Counter
	wg.Add(3)
	// Declare Channels
	randoms := make(chan int)
	fibs := make(chan fibvalue)
	// Launching 3 goroutines
	go randomCounter(randoms)           // First stage of pipeline
	go generateFibonacci(fibs, randoms) // Second stage of pipeline
	go printFibonacci(fibs)             // Third stage of pipeline
	// Wait for completing all goroutines
	wg.Wait()
}
